def tri (tab):

    i = ...
    j = ...
    while i != j:
        if tab[i] == 0:
            i = ...
        else:
            valeur = tab[j]
            tab[j] = ...
            ...
            j = ...
        ...